import { Container } from "@/components/ui/Container";
import Link from "next/link";

export const metadata = {
  title: "Terms of Service | ENVRT",
  description:
    "Terms of Service for the ENVRT sustainability data platform, including dashboards, Digital Product Passports, and reports.",
};

export default function TermsPage() {
  return (
    <div className="pt-28 pb-16">
      <Container>
        <div className="mx-auto max-w-2xl">
          <h1 className="text-4xl font-bold tracking-tight text-envrt-charcoal">
            Terms of service
          </h1>
          <p className="mt-4 text-sm text-envrt-muted">
            Last updated: February 2026
          </p>

          <div className="mt-8 space-y-8 text-sm leading-relaxed text-envrt-charcoal/70">
            {/* ── 1. About these terms ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                1. About these terms
              </h2>
              <p>
                These terms govern your use of the ENVRT platform and related
                services, including the website at envrt.com, the brand dashboard at
                dashboard.envrt.com, public Digital Product Passport pages at
                dpp.envrt.com, and hosted reports at reports.envrt.com.
              </p>
              <p>
                By creating an account or using our Services, you agree to these
                terms. If you are using the Services on behalf of an organisation, you
                confirm that you have authority to bind that organisation to these
                terms.
              </p>
              <p>
                We may update these terms from time to time. See Section&nbsp;17 for
                details on how we communicate changes.
              </p>

              <h3 className="text-base font-semibold text-envrt-charcoal">
                Key definitions
              </h3>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  <strong>&quot;Services&quot;</strong> means the ENVRT platform,
                  dashboards, DPP hosting, report hosting, APIs, and related tools
                  provided by us.
                </li>
                <li>
                  <strong>&quot;Customer&quot;</strong> or{" "}
                  <strong>&quot;Brand&quot;</strong> means the organisation that has
                  subscribed to or contracted for the Services.
                </li>
                <li>
                  <strong>&quot;User&quot;</strong> means any individual who accesses
                  the Services, whether as a brand team member, supplier
                  representative, or visitor.
                </li>
                <li>
                  <strong>&quot;DPP&quot;</strong> means a Digital Product Passport
                  page generated through the platform.
                </li>
                <li>
                  <strong>&quot;Content&quot;</strong> means any data, text, images, or
                  other materials uploaded to or entered into the platform by a
                  Customer or User.
                </li>
                <li>
                  <strong>&quot;Evidence&quot;</strong> means documents, PDFs, images,
                  or other files uploaded as supporting evidence within the dashboard.
                </li>
                <li>
                  <strong>&quot;Outputs&quot;</strong> means any modelled metrics,
                  estimates, visualisations, or reports generated by the platform based
                  on Content.
                </li>
              </ul>
            </section>

            {/* ── 2. Eligibility and accounts ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                2. Eligibility and accounts
              </h2>
              <p>
                Access to the dashboard requires an account. Users must be authorised
                by a Customer to access that Customer&apos;s workspace.
              </p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  You are responsible for keeping your login credentials secure.
                </li>
                <li>
                  You must notify us promptly if you become aware of any unauthorised
                  use of your account.
                </li>
                <li>
                  We may suspend or restrict access to accounts in cases of suspected
                  misuse, security concerns, or non-payment. Where possible, we will
                  provide notice before doing so.
                </li>
              </ul>
            </section>

            {/* ── 3. Services and scope ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                3. Services and scope
              </h2>
              <p>ENVRT provides:</p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  Brand dashboards for managing product data, supply chain
                  information, and evidence
                </li>
                <li>
                  Data collection forms for gathering inputs from brands and suppliers
                </li>
                <li>
                  Generated Outputs, including modelled lifecycle metrics (such as
                  CO2e and water scarcity estimates) and traceability visualisations
                </li>
                <li>Hosted public DPP pages</li>
                <li>Hosted reports</li>
              </ul>
              <p>
                Outputs are modelled estimates. They are generated from the data
                available at the time of calculation. Their accuracy depends on the
                quality and completeness of the inputs provided. See Section&nbsp;10
                for important disclaimers.
              </p>
              <p>
                We may add, modify, or discontinue features over time as we improve
                the platform. Where changes are material, we will communicate them to
                account owners.
              </p>
            </section>

            {/* ── 4. Customer responsibilities ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                4. Customer responsibilities
              </h2>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  You must have the necessary rights to upload Content and Evidence to
                  the platform. This includes any data provided by or on behalf of
                  your supply chain.
                </li>
                <li>
                  You are responsible for the accuracy of the information you provide.
                  Outputs are only as reliable as the inputs they are based on.
                </li>
                <li>
                  You are responsible for any claims you make publicly using Outputs
                  from the platform. This includes statements on product labels,
                  marketing materials, and public DPP pages.
                </li>
                <li>
                  You control what is published on your public DPP pages. We host the
                  pages; you decide the content.
                </li>
              </ul>
            </section>

            {/* ── 5. Public DPP content ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                5. Public DPP content
              </h2>
              <p>
                DPP pages hosted at dpp.envrt.com may be accessed by anyone with the
                link or QR code. They are public by design.
              </p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  We are not responsible for how third parties access, interpret, or
                  use information displayed on public DPP pages.
                </li>
                <li>
                  Brands must ensure that public DPP content is not misleading. It is
                  the Brand&apos;s responsibility to review disclosures for accuracy
                  before publishing.
                </li>
              </ul>
            </section>

            {/* ── 6. Evidence, confidentiality, and privacy ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                6. Evidence uploads, confidentiality, and privacy
              </h2>
              <p>
                Evidence and internal supplier documents uploaded through the
                dashboard are private by default. We apply access controls to restrict
                who can view this data.
              </p>
              <p>
                While we take reasonable steps to protect private data, no system is
                completely secure. We do not guarantee absolute security. See our{" "}
                <Link
                  href="/privacy"
                  className="underline hover:text-envrt-charcoal"
                >
                  Privacy Policy
                </Link>{" "}
                for details on how we process, retain, and protect personal data.
              </p>
              <p>
                Enterprise agreements may include additional confidentiality terms
                where applicable.
              </p>
            </section>

            {/* ── 7. Acceptable use ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                7. Acceptable use
              </h2>
              <p>When using the Services, you must not:</p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  Use the Services for any unlawful purpose or in violation of any
                  applicable law or regulation
                </li>
                <li>
                  Upload Content that infringes the intellectual property or privacy
                  rights of others
                </li>
                <li>
                  Distribute malware, viruses, or any other harmful code through the
                  platform
                </li>
                <li>
                  Scrape, crawl, or extract data from the Services in a way that
                  disrupts or degrades the platform for others
                </li>
                <li>
                  Attempt to reverse engineer, decompile, or disassemble any part of
                  the platform
                </li>
                <li>
                  Interfere with the operation of the Services or bypass access
                  controls
                </li>
              </ul>
            </section>

            {/* ── 8. Intellectual property ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                8. Intellectual property
              </h2>

              <h3 className="text-base font-semibold text-envrt-charcoal">
                Your content
              </h3>
              <p>
                You retain ownership of all Content and Evidence you upload to the
                platform. By uploading Content, you grant ENVRT a limited licence to
                host, process, and display it as necessary to provide the Services.
              </p>

              <h3 className="text-base font-semibold text-envrt-charcoal">
                Our platform
              </h3>
              <p>
                ENVRT retains ownership of the platform, software, documentation,
                templates, site design, and all other materials we create. Nothing in
                these terms transfers ownership of our intellectual property to you.
              </p>

              <h3 className="text-base font-semibold text-envrt-charcoal">
                Licence to use
              </h3>
              <p>
                During your active subscription, we grant you a limited,
                non-exclusive, non-transferable licence to use the Services in
                accordance with these terms.
              </p>

              <h3 className="text-base font-semibold text-envrt-charcoal">
                Embeddable widgets and branding
              </h3>
              <p>
                If you use embeddable widgets, QR code assets, or other materials
                provided by ENVRT, you must use them in accordance with any guidelines
                we provide. &quot;Powered by ENVRT&quot; branding may appear on public
                pages and widgets unless otherwise agreed.
              </p>
            </section>

            {/* ── 9. Fees and payment ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                9. Fees and payment
              </h2>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  Fees for the Services are set out in your order form, invoice, or on
                  our pricing page.
                </li>
                <li>
                  All fees are exclusive of applicable taxes unless stated otherwise.
                </li>
                <li>
                  Late payment may result in suspension of access to the Services. We
                  will provide reasonable notice before suspending for non-payment.
                </li>
                <li>
                  Refunds are handled as set out in your order form or as required by
                  applicable law.
                </li>
              </ul>
            </section>

            {/* ── 10. Disclaimers ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                10. Disclaimers
              </h2>
              <p>
                Outputs generated by the platform are provided for informational and
                decision-support purposes. They are modelled estimates based on the
                data available at the time of generation.
              </p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  Outputs do not constitute legal advice, certification, audit
                  opinions, or formal assurance of any kind.
                </li>
                <li>
                  We do not represent that Outputs will be accepted by any particular
                  regulator, standard body, or third party.
                </li>
                <li>
                  To the extent permitted by law, the Services are provided &quot;as
                  is&quot; without warranties of any kind, whether express or implied,
                  including implied warranties of merchantability, fitness for a
                  particular purpose, or accuracy.
                </li>
              </ul>
              <p>
                We work to make the platform as useful and reliable as possible, but
                we cannot promise that it will always be error-free or uninterrupted.
              </p>
            </section>

            {/* ── 11. Limitation of liability ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                11. Limitation of liability
              </h2>
              <p>
                To the maximum extent permitted by applicable law:
              </p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  We are not liable for any indirect, incidental, consequential, or
                  special losses, including loss of profits, revenue, data, or
                  business opportunity, arising from your use of the Services.
                </li>
                <li>
                  Our total aggregate liability for any claims arising under or in
                  connection with these terms is limited to the fees paid by you in
                  the{" "}
                  <strong>
                    12&nbsp;months
                  </strong>{" "}
                  preceding the event giving rise to the claim.
                </li>
              </ul>
              <p>
                Nothing in these terms excludes or limits liability for fraud, for
                death or personal injury caused by negligence, or for any other
                liability that cannot be excluded or limited under applicable law.
              </p>
            </section>

            {/* ── 12. Availability and maintenance ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                12. Availability and maintenance
              </h2>
              <p>
                We aim to keep the Services available, but they may be temporarily
                unavailable during scheduled maintenance, updates, or unexpected
                outages.
              </p>
              <p>
                We do not offer a specific uptime commitment unless agreed in writing
                as part of a separate service-level agreement.
              </p>
            </section>

            {/* ── 13. Term and termination ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                13. Term and termination
              </h2>
              <p>
                These terms take effect when you create an account or sign an order
                form with us. They remain in effect for the duration of your
                subscription or until terminated.
              </p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  Either party may terminate for material breach if the breach is not
                  remedied within a reasonable period after written notice.
                </li>
                <li>
                  We may terminate or suspend access for misuse, security risks, or
                  continued non-payment.
                </li>
                <li>
                  On termination, your access to the dashboard will be removed. We
                  will provide a reasonable window (30 days) for you to export your data.{" "}
                </li>
                <li>
                  After the export window, we will delete or anonymise your data in
                  line with our{" "}
                  <Link
                    href="/privacy"
                    className="underline hover:text-envrt-charcoal"
                  >
                    Privacy Policy
                  </Link>
                  , unless we are required to retain it by law.
                </li>
              </ul>
            </section>

            {/* ── 14. Third-party services ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                14. Third-party services
              </h2>
              <p>
                We use third-party providers for hosting, storage, authentication,
                analytics, and other infrastructure. We are not responsible for
                outages, errors, or data loss caused by events beyond our reasonable
                control, including failures of third-party services.
              </p>
            </section>

            {/* ── 15. Changes to the Services ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                15. Changes to the Services
              </h2>
              <p>
                We may update, modify, or add new features to the Services over time.
                We may also update documentation and help materials.
              </p>
              <p>
                Where changes are material, we will aim to communicate them to account
                owners in advance. Continued use of the Services after changes take
                effect constitutes acceptance of those changes.
              </p>
            </section>

            {/* ── 16. Governing law and disputes ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                16. Governing law and disputes
              </h2>
              <p>
                These terms are governed by the laws of England and Wales. Any
                disputes arising from these terms will be subject to the exclusive
                jurisdiction of the courts of England and Wales.
              </p>
              <p>
                If you have a concern, we encourage you to contact us first so we can
                try to resolve it informally. See Section&nbsp;18 for contact details.
              </p>
            </section>

            {/* ── 17. Updates to these terms ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                17. Updates to these terms
              </h2>
              <p>
                We may revise these terms from time to time. When we make changes, we
                will update the &quot;Last updated&quot; date at the top of this page.
              </p>
              <p>
                For significant changes, we will notify account holders by email or
                through the dashboard. If you do not agree with the revised terms, you
                may stop using the Services and close your account.
              </p>
            </section>

            {/* ── 18. Contact ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                18. Contact
              </h2>
              <p>
                If you have questions about these terms, contact us at:
              </p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  <strong>Support:</strong>{" "}
                  <a
                    href="mailto:hello@envrt.com"
                    className="underline hover:text-envrt-charcoal"
                  >
                    hello@envrt.com
                  </a>
                </li>
                <li>
                  <strong>Legal and privacy:</strong>{" "}
                  <a
                    href="mailto:privacy@envrt.com"
                    className="underline hover:text-envrt-charcoal"
                  >
                    privacy@envrt.com
                  </a>
                </li>
              </ul>
              {/* Replace with your registered company address */}
              <p>
                ENVRT Ltd
                <br />
                {/* [Street address] */}
                <br />
                {/* [City, Postcode] */}
                <br />
                United Kingdom
              </p>
            </section>

            {/* ── Related policies ── */}
            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-envrt-charcoal">
                Related policies
              </h2>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  <Link
                    href="/privacy"
                    className="underline hover:text-envrt-charcoal"
                  >
                    Privacy Policy
                  </Link>
                </li>
                {/* Uncomment when cookie policy page exists */}
                {/* <li>
                  <Link
                    href="/cookies"
                    className="underline hover:text-envrt-charcoal"
                  >
                    Cookie Policy
                  </Link>
                </li> */}
              </ul>
            </section>
          </div>
        </div>
      </Container>
    </div>
  );
}
