import type { Metadata } from "next";
import {
  LegalShell,
  LegalP,
  LegalH3,
  LegalUl,
  LegalLi,
  LegalStrong,
  LegalLink,
  type LegalSection,
} from "@/components/v3/LegalShell";

export const metadata: Metadata = {
  title: "Terms of service | ENVRT",
  description:
    "Terms governing access to and use of the ENVRT platform, including data ownership, supplier evidence handling and methodology.",
  alternates: { canonical: "/terms" },
};

const SECTIONS: LegalSection[] = [
  {
    index: "01",
    title: "About these terms",
    body: (
      <>
        <LegalP>
          These terms govern your use of the ENVRT platform and related
          services, including the website at envrt.com, the brand dashboard at
          dashboard.envrt.com, public Digital Product Passport pages at
          dpp.envrt.com, and hosted reports at reports.envrt.com.
        </LegalP>
        <LegalP>
          By creating an account, subscribing to a plan, accepting an
          invitation, or simply browsing or accessing any part of our Services,
          you agree to these terms. These terms apply equally to all users,
          including paying subscribers, free trial or pilot users, admin users,
          and anonymous visitors to our websites and public DPP pages. If you
          are using the Services on behalf of an organisation, you confirm that
          you have authority to bind that organisation to these terms.
        </LegalP>
        <LegalP>
          We may update these terms from time to time. See section 18 for
          details on how we communicate changes.
        </LegalP>

        <LegalH3>Key definitions</LegalH3>
        <LegalUl>
          <LegalLi>
            <LegalStrong>&quot;Services&quot;</LegalStrong> means the ENVRT
            platform, dashboards, DPP hosting, report hosting, APIs, and
            related tools provided by us.
          </LegalLi>
          <LegalLi>
            <LegalStrong>&quot;Customer&quot;</LegalStrong> or{" "}
            <LegalStrong>&quot;Brand&quot;</LegalStrong> means the organisation
            that has subscribed to or contracted for the Services.
          </LegalLi>
          <LegalLi>
            <LegalStrong>&quot;User&quot;</LegalStrong> means any individual
            who accesses the Services, whether as a brand team member, supplier
            representative, or visitor.
          </LegalLi>
          <LegalLi>
            <LegalStrong>&quot;DPP&quot;</LegalStrong> means a Digital Product
            Passport page generated through the platform.
          </LegalLi>
          <LegalLi>
            <LegalStrong>&quot;Content&quot;</LegalStrong> means any data,
            text, images, or other materials uploaded to or entered into the
            platform by a Customer or User.
          </LegalLi>
          <LegalLi>
            <LegalStrong>&quot;Evidence&quot;</LegalStrong> means documents,
            PDFs, images, or other files uploaded as supporting evidence within
            the dashboard.
          </LegalLi>
          <LegalLi>
            <LegalStrong>&quot;Outputs&quot;</LegalStrong> means any modelled
            metrics, estimates, visualisations, or reports generated by the
            platform based on Content.
          </LegalLi>
        </LegalUl>
      </>
    ),
  },
  {
    index: "02",
    title: "Eligibility and accounts",
    body: (
      <>
        <LegalP>
          Access to the dashboard requires an account. Users must be authorised
          by a Customer to access that Customer&apos;s workspace.
        </LegalP>
        <LegalUl>
          <LegalLi>
            You are responsible for keeping your login credentials secure.
          </LegalLi>
          <LegalLi>
            You must notify us promptly if you become aware of any unauthorised
            use of your account.
          </LegalLi>
          <LegalLi>
            We may suspend or restrict access to accounts in cases of suspected
            misuse, security concerns, or non-payment. Where possible, we will
            provide notice before doing so.
          </LegalLi>
        </LegalUl>
      </>
    ),
  },
  {
    index: "03",
    title: "Services and scope",
    body: (
      <>
        <LegalP>ENVRT provides:</LegalP>
        <LegalUl>
          <LegalLi>
            Brand dashboards for managing product data, supply chain
            information, and evidence
          </LegalLi>
          <LegalLi>
            Data collection forms for gathering inputs from brands and
            suppliers
          </LegalLi>
          <LegalLi>
            Generated Outputs, including modelled lifecycle metrics (such as
            CO2e and water scarcity estimates) and transparency visualisations
          </LegalLi>
          <LegalLi>Hosted public DPP pages</LegalLi>
          <LegalLi>Hosted reports</LegalLi>
        </LegalUl>
        <LegalP>
          Outputs are modelled estimates. They are generated from the data
          available at the time of calculation. Their accuracy depends on the
          quality and completeness of the inputs provided. See section 11 for
          important disclaimers.
        </LegalP>
        <LegalP>
          We may add, modify, or discontinue features over time as we improve
          the platform. Where changes are material, we will communicate them to
          account owners.
        </LegalP>
      </>
    ),
  },
  {
    index: "04",
    title: "Customer responsibilities",
    body: (
      <LegalUl>
        <LegalLi>
          You must have the necessary rights to upload Content and Evidence to
          the platform. This includes any data provided by or on behalf of your
          supply chain.
        </LegalLi>
        <LegalLi>
          You are responsible for the accuracy of the information you provide.
          Outputs are only as reliable as the inputs they are based on.
        </LegalLi>
        <LegalLi>
          You are responsible for any claims you make publicly using Outputs
          from the platform. This includes statements on product labels,
          marketing materials, and public DPP pages.
        </LegalLi>
        <LegalLi>
          You control what is published on your public DPP pages. We host the
          pages; you decide the content.
        </LegalLi>
      </LegalUl>
    ),
  },
  {
    index: "05",
    title: "Public DPP content",
    body: (
      <>
        <LegalP>
          DPP pages hosted at dpp.envrt.com may be accessed by anyone with the
          link or QR code. They are public by design.
        </LegalP>
        <LegalUl>
          <LegalLi>
            We are not responsible for how third parties access, interpret, or
            use information displayed on public DPP pages.
          </LegalLi>
          <LegalLi>
            Brands must ensure that public DPP content is not misleading. It is
            the Brand&apos;s responsibility to review disclosures for accuracy
            before publishing.
          </LegalLi>
        </LegalUl>
      </>
    ),
  },
  {
    index: "06",
    title: "Evidence uploads, confidentiality and privacy",
    body: (
      <>
        <LegalP>
          Evidence and internal supplier documents uploaded through the
          dashboard are private by default. We apply access controls to
          restrict who can view this data.
        </LegalP>
        <LegalP>
          While we take reasonable steps to protect private data, no system is
          completely secure. We do not guarantee absolute security. See our{" "}
          <LegalLink href="//privacy">Privacy policy</LegalLink> for
          details on how we process, retain and protect personal data.
        </LegalP>
        <LegalP>
          Enterprise agreements may include additional confidentiality terms
          where applicable.
        </LegalP>
      </>
    ),
  },
  {
    index: "07",
    title: "Analytics and data collection",
    body: (
      <>
        <LegalP>
          We collect anonymous usage data across the platform to improve our
          services, monitor performance, and understand how the platform is
          used. This section summarises what we collect. For full details, see
          our{" "}
          <LegalLink href="//privacy">Privacy policy</LegalLink>.
        </LegalP>

        <LegalH3>Public DPP pages</LegalH3>
        <LegalP>
          We collect anonymous view data on public Digital Product Passport
          pages. This includes page path, referrer URL, UTM parameters, device
          type, screen resolution, browser language and approximate location
          (country, region and city derived from server-side request
          headers). We do not store IP addresses, use cookies, use localStorage
          fingerprinting or perform any cross-site tracking on DPP pages.
        </LegalP>

        <LegalH3>Marketing website</LegalH3>
        <LegalP>
          We collect anonymous analytics on envrt.com using a lightweight
          first-party beacon. This includes page path, referrer URL, UTM
          parameters, device type, screen resolution, browser language,
          approximate location (from server-side request headers), scroll
          depth, and time on page. Sessions are grouped using a sessionStorage
          identifier that is automatically cleared when the browser tab is
          closed. We do not use cookies, localStorage fingerprinting, or any
          form of cross-site tracking on the marketing site.
        </LegalP>

        <LegalH3>Dashboard</LegalH3>
        <LegalP>
          For authenticated users on the brand dashboard, we collect usage data
          associated with the user&apos;s account. This includes page path,
          page title, session identifier (sessionStorage, cleared on tab
          close), time on page, scroll depth, device type, screen resolution,
          browser language, approximate location (from server-side request
          headers), and navigation flow. This data is used for product
          improvement and to support the services we provide to our customers.
        </LegalP>

        <LegalH3>What we do not do</LegalH3>
        <LegalUl>
          <LegalLi>
            We do not use third-party tracking scripts, advertising pixels, or
            retargeting tools anywhere on the platform.
          </LegalLi>
          <LegalLi>We do not store IP addresses in our analytics data.</LegalLi>
          <LegalLi>
            We do not use cookies or localStorage for analytics purposes.
            Session grouping relies solely on sessionStorage, which is cleared
            when the browser tab is closed.
          </LegalLi>
          <LegalLi>
            We do not perform cross-site tracking or share analytics data with
            third parties.
          </LegalLi>
          <LegalLi>
            Approximate geographic location is derived from server-side request
            headers provided by our hosting infrastructure, not from GPS, IP
            geolocation databases, or device-level location services.
          </LegalLi>
        </LegalUl>

        <LegalP>
          The legal basis for this data collection is legitimate interest under
          GDPR Article 6(1)(f). We use first-party product analytics to improve
          the platform, monitor reliability, and understand usage patterns. For
          authenticated dashboard users, analytics also fall within the scope
          of the existing contractual relationship. By using any part of the
          Services, you acknowledge and accept these data collection practices.
        </LegalP>
      </>
    ),
  },
  {
    index: "08",
    title: "Acceptable use",
    body: (
      <>
        <LegalP>When using the Services, you must not:</LegalP>
        <LegalUl>
          <LegalLi>
            Use the Services for any unlawful purpose or in violation of any
            applicable law or regulation
          </LegalLi>
          <LegalLi>
            Upload Content that infringes the intellectual property or privacy
            rights of others
          </LegalLi>
          <LegalLi>
            Distribute malware, viruses, or any other harmful code through the
            platform
          </LegalLi>
          <LegalLi>
            Scrape, crawl, or extract data from the Services in a way that
            disrupts or degrades the platform for others
          </LegalLi>
          <LegalLi>
            Attempt to reverse engineer, decompile, or disassemble any part of
            the platform
          </LegalLi>
          <LegalLi>
            Interfere with the operation of the Services or bypass access
            controls
          </LegalLi>
        </LegalUl>
      </>
    ),
  },
  {
    index: "09",
    title: "Intellectual property",
    body: (
      <>
        <LegalH3>Your content</LegalH3>
        <LegalP>
          You retain ownership of all Content and Evidence you upload to the
          platform. By uploading Content, you grant ENVRT a limited licence to
          host, process and display it as necessary to provide the Services.
        </LegalP>

        <LegalH3>Our platform</LegalH3>
        <LegalP>
          ENVRT retains ownership of the platform, software, documentation,
          templates, site design, and all other materials we create. Nothing in
          these terms transfers ownership of our intellectual property to you.
        </LegalP>

        <LegalH3>Licence to use</LegalH3>
        <LegalP>
          During your active subscription, we grant you a limited,
          non-exclusive, non-transferable licence to use the Services in
          accordance with these terms.
        </LegalP>

        <LegalH3>Embeddable widgets and branding</LegalH3>
        <LegalP>
          If you use embeddable widgets, QR code assets, or other materials
          provided by ENVRT, you must use them in accordance with any
          guidelines we provide. &quot;Powered by ENVRT&quot; branding may
          appear on public pages and widgets unless otherwise agreed.
        </LegalP>
      </>
    ),
  },
  {
    index: "10",
    title: "Fees and payment",
    body: (
      <>
        <LegalUl>
          <LegalLi>
            Fees for the Services are set out in your order form, invoice, or
            on our pricing page.
          </LegalLi>
          <LegalLi>
            All fees are exclusive of applicable taxes unless stated otherwise.
          </LegalLi>
          <LegalLi>
            Late payment may result in suspension of access to the Services.
            We will provide reasonable notice before suspending for
            non-payment.
          </LegalLi>
          <LegalLi>
            Refunds are handled as set out in your order form or as required by
            applicable law.
          </LegalLi>
        </LegalUl>

        <LegalH3>Self-serve subscriptions</LegalH3>
        <LegalP>
          Where you subscribe to a plan through our website, the following
          additional terms apply:
        </LegalP>
        <LegalUl>
          <LegalLi>
            Payments are processed securely by{" "}
            <LegalLink href="https://stripe.com" external>
              Stripe
            </LegalLink>
            . ENVRT does not store your card details. All payment data is
            handled in accordance with Stripe&apos;s security and privacy
            policies.
          </LegalLi>
          <LegalLi>
            Subscriptions are billed on a recurring basis (monthly or annually,
            depending on the plan selected at checkout).
          </LegalLi>
          <LegalLi>
            All subscriptions have a{" "}
            <LegalStrong>minimum commitment of 6 months</LegalStrong>. You may
            not cancel your subscription before the minimum commitment period
            has elapsed. After the minimum commitment, subscriptions continue
            on a rolling basis until cancelled.
          </LegalLi>
          <LegalLi>
            If a scheduled payment fails, we will retry the charge in
            accordance with our payment provider&apos;s retry policy (typically
            up to 4 attempts within 7 days). If all retry attempts fail, your
            subscription may be marked as overdue and access to the Services
            may be restricted until payment is resolved.
          </LegalLi>
          <LegalLi>
            You may update your payment method or billing details through the
            Stripe customer portal. A link can be provided on request.
          </LegalLi>
          <LegalLi>
            Pricing is displayed in the currency selected at checkout. Where a
            price is not available in the selected currency, we may charge in
            GBP at the equivalent rate.
          </LegalLi>
        </LegalUl>
      </>
    ),
  },
  {
    index: "11",
    title: "Disclaimers",
    body: (
      <>
        <LegalP>
          Outputs generated by the platform are provided for informational and
          decision-support purposes. They are modelled estimates based on the
          data available at the time of generation.
        </LegalP>
        <LegalUl>
          <LegalLi>
            Outputs do not constitute legal advice, certification, audit
            opinions, or formal assurance of any kind.
          </LegalLi>
          <LegalLi>
            We do not represent that Outputs will be accepted by any particular
            regulator, standard body, or third party.
          </LegalLi>
          <LegalLi>
            To the extent permitted by law, the Services are provided
            &quot;as is&quot; without warranties of any kind, whether express
            or implied, including implied warranties of merchantability,
            fitness for a particular purpose, or accuracy.
          </LegalLi>
        </LegalUl>
        <LegalP>
          We work to make the platform as useful and reliable as possible, but
          we do not guarantee that the platform will always be error-free or
          uninterrupted.
        </LegalP>

        <LegalH3>Verification levels</LegalH3>
        <LegalP>
          Outputs may include verification labels such as
          &quot;declared&quot;, &quot;modelled&quot;, &quot;validated&quot;,
          or &quot;verified&quot; to describe the basis of individual data
          points within a product&apos;s supply chain. These labels reflect the
          nature and quality of the supporting evidence available at the time
          of assessment. &quot;Declared&quot; and &quot;modelled&quot; indicate
          that the data was provided by the brand or derived from secondary
          sources and industry databases. &quot;Validated&quot; indicates that
          ENVRT has reviewed available supporting evidence, which may include
          supplier engagement and cross-referencing against known data sources,
          but this does not constitute formal third-party certification.
          &quot;Verified&quot; indicates that the data has been independently
          verified by a qualified third party. ENVRT does not independently
          verify the accuracy of data provided by brands or their supply
          chains. Brands are responsible for ensuring that the information they
          provide is accurate and supportable. Consumers viewing Digital
          Product Passport pages should be aware that the environmental data
          presented is based on the best available information at the time of
          assessment and may be subject to change as new data becomes
          available.
        </LegalP>

        <LegalH3>Methodology</LegalH3>
        <LegalP>
          ENVRT&apos;s lifecycle modelling methodology is aligned with
          recognised frameworks including ISO 14040/14044 and the EU Product
          Environmental Footprint Category Rules (PEFCR) for apparel and
          footwear. &quot;Aligned with&quot; means the methodology follows the
          principles and structure of these standards. It does not mean that
          ENVRT&apos;s methodology, platform, or Outputs have been
          independently certified, accredited, or audited against these
          standards by a third-party body.
        </LegalP>
      </>
    ),
  },
  {
    index: "12",
    title: "Limitation of liability",
    body: (
      <>
        <LegalP>To the maximum extent permitted by applicable law:</LegalP>
        <LegalUl>
          <LegalLi>
            We are not liable for any indirect, incidental, consequential, or
            special losses, including loss of profits, revenue, data, or
            business opportunity, arising from your use of the Services.
          </LegalLi>
          <LegalLi>
            Our total aggregate liability for any claims arising under or in
            connection with these terms is limited to the fees paid by you in
            the <LegalStrong>12 months</LegalStrong> preceding the event giving
            rise to the claim.
          </LegalLi>
        </LegalUl>
        <LegalP>
          Nothing in these terms excludes or limits liability for fraud, for
          death or personal injury caused by negligence, or for any other
          liability that cannot be excluded or limited under applicable law.
        </LegalP>
      </>
    ),
  },
  {
    index: "13",
    title: "Availability and maintenance",
    body: (
      <>
        <LegalP>
          We aim to keep the Services available, but they may be temporarily
          unavailable during scheduled maintenance, updates, or unexpected
          outages.
        </LegalP>
        <LegalP>
          We do not offer a specific uptime commitment unless agreed in writing
          as part of a separate service-level agreement.
        </LegalP>
      </>
    ),
  },
  {
    index: "14",
    title: "Term and termination",
    body: (
      <>
        <LegalP>
          These terms take effect when you create an account or sign an order
          form with us. They remain in effect for the duration of your
          subscription or until terminated.
        </LegalP>
        <LegalUl>
          <LegalLi>
            Self-serve subscriptions are subject to a minimum commitment period
            of 6 months from the date of purchase (see section 10).
            Cancellation requests made before the minimum commitment period has
            elapsed will take effect at the end of the commitment period.
          </LegalLi>
          <LegalLi>
            After the minimum commitment period, you may cancel your
            subscription at any time. Cancellation will take effect at the end
            of the current billing period.
          </LegalLi>
          <LegalLi>
            Either party may terminate for material breach if the breach is not
            remedied within a reasonable period after written notice.
          </LegalLi>
          <LegalLi>
            We may terminate or suspend access for misuse, security risks, or
            continued non-payment.
          </LegalLi>
          <LegalLi>
            On termination, your access to the dashboard will be removed. We
            will provide a reasonable window (30 days) for you to export your
            data.
          </LegalLi>
          <LegalLi>
            After the export window, we will delete or anonymise your data in
            line with our{" "}
            <LegalLink href="//privacy">Privacy policy</LegalLink>,
            unless we are required to retain it by law.
          </LegalLi>
        </LegalUl>
      </>
    ),
  },
  {
    index: "15",
    title: "Third-party services",
    body: (
      <LegalP>
        We use third-party providers for hosting, storage, authentication,
        analytics, and other infrastructure. We are not responsible for
        outages, errors, or data loss caused by events beyond our reasonable
        control, including failures of third-party services.
      </LegalP>
    ),
  },
  {
    index: "16",
    title: "Changes to the Services",
    body: (
      <>
        <LegalP>
          We may update, modify, or add new features to the Services over time.
          We may also update documentation and help materials.
        </LegalP>
        <LegalP>
          Where changes are material, we will aim to communicate them to
          account owners in advance. Continued use of the Services after
          changes take effect constitutes acceptance of those changes.
        </LegalP>
      </>
    ),
  },
  {
    index: "17",
    title: "Governing law and disputes",
    body: (
      <>
        <LegalP>
          These terms are governed by the laws of England and Wales. Any
          disputes arising from these terms will be subject to the exclusive
          jurisdiction of the courts of England and Wales.
        </LegalP>
        <LegalP>
          If you have a concern, we encourage you to contact us first so we can
          try to resolve it informally. See section 19 for contact details.
        </LegalP>
      </>
    ),
  },
  {
    index: "18",
    title: "Updates to these terms",
    body: (
      <>
        <LegalP>
          We may revise these terms from time to time. When we make changes, we
          will update the &quot;Last updated&quot; date at the top of this
          page.
        </LegalP>
        <LegalP>
          For significant changes, we will notify account holders by email or
          through the dashboard. If you do not agree with the revised terms,
          you may stop using the Services and close your account.
        </LegalP>
      </>
    ),
  },
  {
    index: "19",
    title: "Contact",
    body: (
      <>
        <LegalP>
          If you have questions about these terms, contact us at:
        </LegalP>
        <LegalP>
          <LegalLink href="mailto:info@envrt.com">info@envrt.com</LegalLink>
        </LegalP>
        <LegalP>ENVRT Ltd, United Kingdom.</LegalP>
        <LegalP>
          Related:{" "}
          <LegalLink href="//privacy">Privacy policy</LegalLink>.
        </LegalP>
      </>
    ),
  },
];

export default function TermsV3Page() {
  return (
    <LegalShell
      cornerLabel="Terms"
      pageTitle="Terms of service"
      pageBody="The contract between ENVRT and anyone using the platform, dashboards, public DPP pages or hosted reports. Plain language, no fine-print games."
      lastUpdated="Last updated 1 March 2026"
      sections={SECTIONS}
    />
  );
}
